{
  "use_sim_time": true,
  "frame_id": "sensor_rig",
  "odom_frame_id": "odom",
  "map_frame_id": "map",
  "slam_latch": false,
  "subscribe_scan_cloud": true,
  "subscribe_rgb": false,
  "subscribe_depth": false,
  "subscribe_odom_info": true,
  "approx_sync": true,
  "queue_size": 30,
  "Reg/Strategy": 1,
  "RGBD/ProximityBySpace": true,
  "Grid/3D": true,
  "Grid/RangeMax": 60.0,
  "Optimizer/Strategy": 2,
  "Icp/PointToPlane": true,
  "Icp/Iterations": 10,
  "Icp/VoxelSize": 0.05,
  "Icp/Epsilon": 0.001,
  "Icp/PointToPlaneK": 20,
  "Icp/PointToPlaneRadius": 0.0,
  "Icp/MaxTranslation": 0.2,
  "Icp/MaxRotation": 0.2,
  "Icp/MaxCorrespondenceDistance": 0.2,
  "Icp/CorrespondenceRatio": 0.01,
  "Icp/ReciprocalCorrespondences": false,
  "Icp/OutlierRatio": 0.7,
  "Odom/ScanKeyFrameThr": 0.4,
  "OdomF2M/ScanSubtractRadius": 0.05,
  "OdomF2M/ScanMaxSize": 15000,
  "OdomF2M/BundleAdjustment": false
}
